---
title: 'This is a new post '
author: Alex Michel
date: '2018-06-13'
slug: How do I make a post?
categories:
  - R
tags:
  - sad plot
  - R Markdown
description: Desc
hacker_news_id: ''
lobsters_id: ''
meta_img: /images/image.jpg
---

Is this how you add in stuff? 

```{r}
1 + 1
rnorm(10)  # 10 random numbers
plot(dist ~ speed, cars)  # a scatterplot
```
This is another test at how to add in stuff

```{r}

library(babynames)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(ggthemes)
library(plotly)
library(RColorBrewer)

star_wars <- babynames %>%
  filter(name == "Leah" | name == "Leia") %>% 
  filter(sex == "F") %>% 
  filter(year >= 1975)

plot <- ggplot(star_wars, aes(x = year, 
                           y = prop,  
                           group = name, 
                           color = name)) + 
  geom_line(size = 2) +
  geom_vline(xintercept = 1977, linetype="dashed", 
                color = "blue", size=1) +
  geom_vline(xintercept = 1999, linetype="dashed", 
                color = "blue", size=1) +
  geom_vline(xintercept = 2014, linetype="dashed", 
                color = "blue", size=1) +
  annotate("text", x = 1980, y = 0.01, label = "Star Wars") +
  annotate("text", x = 2004, y = 0.008, label = "Phantom Menace") +
  annotate("text", x = 2009.5, y = 0.005, label = "Force Awakens")

plot
```

